# Generated by Django 2.0.7 on 2019-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_salt',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
