# Generated by Django 2.0.7 on 2018-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersanswers',
            old_name='user_id',
            new_name='user',
        ),
    ]
