# Generated by Django 2.0.7 on 2018-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20180901_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswers',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
