# Generated by Django 2.0.7 on 2018-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20180901_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswers',
            name='user_answer',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
