# Generated by Django 2.0.7 on 2018-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20180901_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_timer',
            field=models.TextField(blank=True, default=0),
        ),
    ]
