# Generated by Django 2.0.7 on 2018-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_test_test_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_lesson_number',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
