# Generated by Django 2.0.7 on 2018-10-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_test_test_lesson_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hints',
            new_name='Hint',
        ),
    ]
