# Generated by Django 2.0.7 on 2018-10-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20181011_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_lesson_number',
            field=models.CharField(max_length=200),
        ),
    ]
