# Generated by Django 2.0.7 on 2018-10-11 17:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20181011_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_tests',
            field=models.CharField(default=1, max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
