# Generated by Django 2.0.7 on 2018-10-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_profile_finished_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
