# Generated by Django 2.0.7 on 2018-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_auto_20181016_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithanswer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='questionwithvariants',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
    ]
