# Generated by Django 2.0.7 on 2018-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_auto_20181212_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='questionwithvariants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
    ]
