# Generated by Django 2.0.7 on 2018-12-12 18:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_auto_20181212_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionwithanswer',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
    ]
