# Generated by Django 2.0.7 on 2019-01-17 14:52

import Test.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_auto_20181212_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswers',
            name='test',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Test.Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionwithanswer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/', validators=[Test.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='questionwithanswer',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/', validators=[Test.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
