# Generated by Django 2.0.7 on 2019-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_auto_20190117_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_lesson_number',
            field=models.IntegerField(),
        ),
    ]
