# Generated by Django 2.0.7 on 2019-02-15 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0016_auto_20190117_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test_result', models.CharField(blank=True, max_length=100)),
                ('second_test_result', models.CharField(blank=True, max_length=100)),
                ('third_test_result', models.CharField(blank=True, max_length=100)),
                ('fourth_test_result', models.CharField(blank=True, max_length=100)),
                ('fifth_test_result', models.CharField(blank=True, max_length=100)),
                ('six_test_result', models.CharField(blank=True, max_length=100)),
                ('seventh_test_result', models.CharField(blank=True, max_length=100)),
                ('eighth_test_result', models.CharField(blank=True, max_length=100)),
                ('ninth_test_result', models.CharField(blank=True, max_length=100)),
                ('tenth_test_result', models.CharField(blank=True, max_length=100)),
                ('eleventh_test_result', models.CharField(blank=True, max_length=100)),
                ('twelfth_test_result', models.CharField(blank=True, max_length=100)),
                ('thirteenth_test_result', models.CharField(blank=True, max_length=100)),
                ('fourteenth_test_result', models.CharField(blank=True, max_length=100)),
                ('fifteenth_test_result', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='questionwithanswer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%D/'),
        ),
    ]
