# Generated by Django 2.0.7 on 2019-02-15 23:19

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0017_auto_20190215_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionwithanswer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='questionwithanswer',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
